### ISSUE TITLE
Problem running on Ubuntu - Error: watch ENOSPC

### ISSUE THREAD

**Issue by felquis** [pagarme/api-reference#1]
I had this problem when running `npm start` no a Ubuntu 16.04

This [link](https://discourse.roots.io/t/gulp-watch-error-on-ubuntu-14-04-solved/3453) helped me on this, The error happens because there's a limit of files that can be watched by default on Ubuntu. And we need to increase this number of files in the `/etc/sysctl.conf` config file, adding this line at the end `fs.inotify.max_user_watches=582222`

The command to add the config bellow is

```shell
echo fs.inotify.max_user_watches=582222 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
```

Att

**Comment by tribudiyono93** [comment]
After my 4 hours, thank you very much.
